//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/30
//  @ Author : 211506335
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueFromKey() {

}

char StaticData::stringValueFromKey() {

}

float StaticData::floatValueFromKey() {

}

bool StaticData::booleanValueFromKey() {

}

cocos2d::CCPoint StaticData::pointValueFromKey() {

}

cocos2d::CCRect StaticData::rectValueFromKey() {

}

cocos2d::CCSize StaticData::sizeValueFromKey() {

}

bool StaticData::init() {

}

void StaticData::StaticData() {

}

StaticData::StaticData() {

}

